const express = require('express');
const UsuarioController = require ('../controller/UsuarioController.js');
const CustomerController = require ('../controller/CustomerController.js');
const AgencyController = require ('../controller/AgencyController.js');
const AccountController = require ('../controller/AccountController.js');
const RegisterController = require ('../controller/RegisterController.js');
const router = express.Router();

router.post('/agency', AgencyController.Insert);
router.get('/agency', AgencyController.SearchAll);
router.get('/agency/:id', AgencyController.SearchOne);
router.put('/agency/:id', AgencyController.Update);
router.delete('/agency/:id', AgencyController.Delete);
router.get('/login', AccountController.SearchLogin);
router.post('/account', AccountController.Insert);
router.get('/account', AccountController.SearchAll);
router.get('/account/:id', AccountController.SearchOne);
router.put('/account/:id', AccountController.Update);
router.get('/account/getbalance/:id', AccountController.GetBalance);
router.put('/account/balance/:id', AccountController.UpdateBalance);
router.put('/account/balancedest/:id', AccountController.UpdateBalanceDest);
router.delete('/account/:id', AccountController.Delete);
router.post('/registers', RegisterController.Insert);
router.get('/registers', RegisterController.SearchAll);
router.get('/registers/:id', RegisterController.SearchOne);
router.put('/registers/:id', RegisterController.Update);
router.delete('/registers/:id', RegisterController.Delete);
router.post('/customers', CustomerController.Insert);
router.get('/customers', CustomerController.SearchAll);
router.get('/customers/:id', CustomerController.SearchOne);
router.put('/customers/:id', CustomerController.Update);
router.delete('/customers/:id', CustomerController.Delete);
router.post('/usuarios', UsuarioController.Insert);
router.get('/usuarios', UsuarioController.SearchAll);
router.get('/usuarios/:id', UsuarioController.SearchOne);
router.put('/usuarios/:id', UsuarioController.Update);
router.delete('/usuarios/:id', UsuarioController.Delete);

module.exports = router;